server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/profile_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: tranleduy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  expiryTime: 3600
  refreshTime: 36000

springdoc:
  api-docs:
    path: /swagger-ui/identity.html
    enabled: true
  swagger-ui:
    operations-sorter: method
